### PR TITLE
Add consult initial form

### PR DESCRIPTION
**Pull request by brandones**
https://github.com/PIH/openmrs-module-pihcore/pull/309

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
It's worth looking at the Primary Care component and see if it's possibly worth reusing that instead of created a new component... specifically, take a look at what we do for Mexico vs Haiti in the primary care component block in the CALF.

**Comment by brandones** [comment]
Sure, reasonable enough. Really I just wish there was no shared config/components/CALF and sites had full control over their own encounter types and how they relate to forms.

**Comment by brandones** [comment]
Oh yeah, it's that Mexico uses their own custom encounter type called "mexico consult" for this, and there's really no appropriate "initial outpatient consult" encounter type in config-pihemr. So actually I still suggest we do it this way.

**Comment by mogoodrich** [comment]
Cool, defer to you, just wanted to make sure you say it was out there.
Yes, part of the config-initiatve CALF refactoring will be to make this more flexible.

**Comment by brandones** [comment]
Thanks @mogoodrich !

**Pull request merged**
