### PR TITLE
Fix compilation for UHM-4354

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-4354

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
If everything still works after removing this, great!

**Comment by mseaton** [comment]
Does this really still work? Are these no longer used anywhere?  It doesn't look like you're installing these into the unit test via iniz...

**Comment by brandones** [comment]
Surprisingly, yes! `mvn clean package` completes successfully.

**Comment by mogoodrich** [comment]
Might be worth seeing if this test is actually running... actually, it might be one we @Ignore but keep around for when we manually want to test the printers?

**Comment by brandones** [comment]
Oh, yes. Yes it's `@ignored`. I suppose I'll run it.

**Comment by mogoodrich** [comment]
Yes @brandones  that's a test that just tries to print an ID Card to a printer connected locally: https://github.com/PIH/openmrs-module-mirebalais/blob/dc9231069c020e0cb4b8792b5ff9e6446bd5b525/api/src/test/java/org/openmrs/module/mirebalais/printer/impl/ZlEmrIdCardPrinterTest.java#L131

We basically just run it manually when we've got an ID Card printer connected to our local machine and are tweaking the layout and want to test.

So there are no asserts at that end or anything, but it should end up printing out a card.  Obviously, no need to test that fully, but would be good to see if the test runs, or if it starts to stack trace with a NPE or something now.

If it does, and it's a pain to fix, we can think about workaround or just documenting and punting until we need it.

**Review by mogoodrich — APPROVED** [review]

**Pull request merged**
