### PR TITLE
Update Haiti occupations list

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/UHM-5234

Screenshot from 2021-03-17 16-10-39
Screenshot from 2021-03-17 16-10-49

### CODE REVIEW

**Comment by brandones** [comment]
The list is now incredibly long; I predict an incoming feature request for a registrationapp change.

It is in the order specified in https://partnersinhealth.sharepoint.com/:x:/s/ZLPEPFARCDCReporting/EQo504jEgUtDsNppSJqQQpwBwUM7nVSYMGI9lCSdB1El7w?e=oY3pc6 up until "Shephard." From "Shephard" to "Professional" are occupations that are not in that Excel sheet. I have included them here because it seems likely that some were unintentional omissions.

**Review by mogoodrich — APPROVED** [review]
Ugh.  Looks like there are a couple with odd capitalization/spacing like nurseAide?

And, yeah, we will probably need a parameter to sort this alphabetically by message code?

Anyway, we can merge this in and review with Ricard.

**Comment by brandones** [comment]
@mogoodrich Yeah I updated those messages after taking the screenshot.

This is sorted in French. On the CES reg page they're sorted in Spanish. I'm not sure we should have the widget sort these automatically. It would be annoying to program that, and provide for it putting "Unemployed" and "Other" at the bottom.

**Comment by mogoodrich** [comment]
Oh, cool... sorting in French works for me!

**Pull request merged**
