### PR TITLE
Have pihemrDeploy link in the site frontend config

### PR DESCRIPTION
**Pull request by brandones**
This is based on my comment in Jira here: https://pihemr.atlassian.net/browse/UHM-5505?focusedCommentId=118659 . This is approach (3), which I think is the best of them.

### CODE REVIEW

**Review by mseaton — COMMENTED** [review]
What worries me is that this is not a solution that will work for everyone using the SDK out of the box for a given distribution.  Ideally, using standard SDK commands would allow all necessary artifacts to end up in the location in an SDK server where they belong.

Is there a reason why we can't have some configuration setting (eg. in openmrs-distro.properties) that defines where to find the frontend configuration, and then when you create/update/deploy a server in the SDK it just copies all files (or symlinks I guess) from that location over to openmrs/<server>/frontend/site?

Perhaps the missing piece is that the SDK is not yet aware of the notion of Initializer configuration at all.  So we might need to tackle those together.

This seems fine for now to get people working, but beyond that I think we should look for more automation and standardization of this within the framework and openmrs-distro.properties configuration.

**Review by mogoodrich — APPROVED** [review]
LMK!

However, when we merge we should send out a quick email to all devs about the (slight) usage change to pihemrDeploy.sh.   Could you write that up?  I've got a group of all the PIH devs worldwide, so happy to send it out.

**Comment by mogoodrich** [comment]
To @mseaton 's comment: I'm probably not understanding, but isn't the issue that SDK *does* copy all the frontend files over during the deploy to the appropriate directiry, the issue is that in the PIH EMR we want to link in the specific "config.json" that is supplied within a country's "config-*" project?  @brandones

**Comment by brandones** [comment]
Yeah, that's exactly it @mogoodrich . @mseaton I think you're right that usually people will want to bundle "assets" like the config.json in their distro—I've suggested allowing this with a `spa.assetsDir` distro.properties key—the trouble is that this wouldn't work for the PIH EMR specifically, since we have one distro with many config files.

**Comment by brandones** [comment]
@mogoodrich Will email you some copy, thanks!

**Pull request merged**
