### PR TITLE
PERU-391: add new analysis requests functionality

### PR DESCRIPTION
**Pull request by mogoodrich**

### CODE REVIEW

**Comment by brandones** [comment]
Sure, assuming you've validated that "analysis requests" is what this is about. I guess this app is to support the specimen collection step of the lab workflow.

**Review by brandones — APPROVED** [review]

**Comment by mogoodrich** [comment]
@brandones correct... but you are also right, we may want to tweak the name as this evolves if it doesn't match what it actually ends up doing...

**Comment by aastupilloses** [comment]
Thanks for your help, @mogoodrich! About the name... if this form usage is to create an analysis request (a document that contains samples collection data and some other related things), I guess it is OK. But maybe we can talk about this later in order to change it!

**Comment by mogoodrich** [comment]
Yeah, I think we may want to tweak the name, but figured it was good to start with this...

**Pull request merged**
