### PR TITLE
MEX-404 Registration form elements should be in Spanish

### PR DESCRIPTION
**Pull request by brandones**
https://pihemr.atlassian.net/browse/MEX-404

### CODE REVIEW

**Comment by brandones** [comment]
It's almost exactly the same as the other one.

**Comment by mogoodrich** [comment]
LGTM, assuming that you are removing the Prospero section as well in this commit

**Comment by lnball** [comment]
> LGTM. One question - are we using Transifex for translations for the mirebalais module, and did these get pulled in from there?

Yes @mseaton .  We are using Transifex for all our modules.

**Comment by lnball** [comment]
Looks good @brandones

**Pull request merged**
